name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  mailer: ^6.4.1
  drift: ^2.1.0
  path: ^1.9.0
  sqlite3: ^2.1.0
  dotenv: ^4.2.0
  json_annotation: ^4.8.0
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  uuid: ^4.5.1
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.2.0
  either_dart: ^1.0.0
  # result_type: ^1.0.0
  sha_red:
    git: https://github.com/s1r1m1r1/sha_red.git
  dart_frog_web_socket: ^1.0.0
  broadcast_bloc: ^0.1.0-dev.2
  synchronized: ^3.4.0
  equatable: ^2.0.7
  bloc_concurrency: ^0.3.0
  get_it:
  injectable: ^2.1.0

dependency_overrides:
  bloc: ^9.0.0
#   sha_red:
#     path: ../sha_red

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  build_runner: ^2.4.0
  drift_dev: ^2.1.0
  freezed: ^3.0.0
  json_serializable: ^6.7.1
  mockito: ^5.5.0
  injectable_generator: ^2.1.0
