name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  mailer: ^6.4.1
  drift: ^2.1.0  
  path: ^1.9.0    
  sqlite3: ^2.1.0 
  dotenv: ^4.2.0
  json_annotation: ^4.8.0
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  uuid: ^4.5.1
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.2.0
  either_dart: ^1.0.0
  orm: ^1.0.5
  # result_type: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  build_runner: ^2.4.0
  drift_dev: ^2.1.0
  freezed: ^3.0.0
  json_serializable: ^6.7.1



 