// Mocks generated by Mockito 5.4.6 from annotations
// in backend/test/features/bot/bot_upgrade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:backend/db_client/dao/unit_dao.dart' as _i8;
import 'package:backend/db_client/db_client.dart' as _i5;
import 'package:backend/features/auth/application/session_socket.dart' as _i16;
import 'package:backend/features/auth/domain/session.dart' as _i3;
import 'package:backend/features/auth/domain/session_repository.dart' as _i12;
import 'package:backend/features/auth/domain/user_repository.dart' as _i10;
import 'package:backend/features/chat/application/letters_broad_manager.dart'
    as _i15;
import 'package:backend/features/game/domain/unit_repository.dart' as _i13;
import 'package:backend/models/user.dart' as _i2;
import 'package:drift/drift.dart' as _i6;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i7;
import 'package:dto/dto.dart' as _i11;
import 'package:game_dto/game_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_1 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnitDto_2 extends _i1.SmartFake implements _i4.UnitDto {
  _FakeUnitDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDbClient_3 extends _i1.SmartFake implements _i5.DbClient {
  _FakeDbClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_4 extends _i1.SmartFake
    implements _i6.DatabaseConnection {
  _FakeDatabaseConnection_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_5 extends _i1.SmartFake
    implements _i6.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_6 extends _i1.SmartFake implements _i6.QueryExecutor {
  _FakeQueryExecutor_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_7 extends _i1.SmartFake
    implements _i7.StreamQueryStore {
  _FakeStreamQueryStore_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_8 extends _i1.SmartFake
    implements _i6.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UnitTableTable_9 extends _i1.SmartFake
    implements _i5.$UnitTableTable {
  _Fake$UnitTableTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SelectedUnitTableTable_10 extends _i1.SmartFake
    implements _i5.$SelectedUnitTableTable {
  _Fake$SelectedUnitTableTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnitDaoManager_11 extends _i1.SmartFake
    implements _i8.UnitDaoManager {
  _FakeUnitDaoManager_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_12<T1> extends _i1.SmartFake implements _i9.Future<T1> {
  _FakeFuture_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_13<T1 extends _i6.Table, D1> extends _i1.SmartFake
    implements _i6.InsertStatement<T1, D1> {
  _FakeInsertStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_14<T extends _i6.Table, D> extends _i1.SmartFake
    implements _i6.UpdateStatement<T, D> {
  _FakeUpdateStatement_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_15<T1 extends _i6.HasResultSet, D>
    extends _i1.SmartFake
    implements _i6.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_16<FirstT extends _i6.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i6.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_17<Row> extends _i1.SmartFake
    implements _i6.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_18<T1 extends _i6.Table, D1> extends _i1.SmartFake
    implements _i6.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_19<T> extends _i1.SmartFake implements _i6.Selectable<T> {
  _FakeSelectable_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_20 extends _i1.SmartFake
    implements _i6.GenerationContext {
  _FakeGenerationContext_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i10.UserRepository {
  @override
  _i9.Future<_i2.User?> getUser({
    _i11.UserId? userId,
    String? email,
    String? confirmationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [], {
              #userId: userId,
              #email: email,
              #confirmationToken: confirmationToken,
            }),
            returnValue: _i9.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i9.Future<_i2.User?>.value(),
          )
          as _i9.Future<_i2.User?>);

  @override
  _i9.Future<_i2.User> createUser(_i11.EmailCredentialDto? createUserDto) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [createUserDto]),
            returnValue: _i9.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#createUser, [createUserDto]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#createUser, [createUserDto]),
              ),
            ),
          )
          as _i9.Future<_i2.User>);

  @override
  _i9.Future<_i2.User> loginUser(_i11.EmailCredentialDto? loginUserDto) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [loginUserDto]),
            returnValue: _i9.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#loginUser, [loginUserDto])),
            ),
            returnValueForMissingStub: _i9.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#loginUser, [loginUserDto])),
            ),
          )
          as _i9.Future<_i2.User>);

  @override
  _i9.Future<_i2.User> confirmEmail(String? confirmationToken) =>
      (super.noSuchMethod(
            Invocation.method(#confirmEmail, [confirmationToken]),
            returnValue: _i9.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#confirmEmail, [confirmationToken]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#confirmEmail, [confirmationToken]),
              ),
            ),
          )
          as _i9.Future<_i2.User>);

  @override
  _i9.Future<List<_i2.User>> getBots() =>
      (super.noSuchMethod(
            Invocation.method(#getBots, []),
            returnValue: _i9.Future<List<_i2.User>>.value(<_i2.User>[]),
            returnValueForMissingStub: _i9.Future<List<_i2.User>>.value(
              <_i2.User>[],
            ),
          )
          as _i9.Future<List<_i2.User>>);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i12.SessionRepository {
  @override
  _i9.Future<_i3.Session> createSession(_i2.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [user]),
            returnValue: _i9.Future<_i3.Session>.value(
              _FakeSession_1(this, Invocation.method(#createSession, [user])),
            ),
            returnValueForMissingStub: _i9.Future<_i3.Session>.value(
              _FakeSession_1(this, Invocation.method(#createSession, [user])),
            ),
          )
          as _i9.Future<_i3.Session>);

  @override
  _i9.Future<_i3.Session> updateSession(_i3.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i9.Future<_i3.Session>.value(
              _FakeSession_1(
                this,
                Invocation.method(#updateSession, [session]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.Session>.value(
              _FakeSession_1(
                this,
                Invocation.method(#updateSession, [session]),
              ),
            ),
          )
          as _i9.Future<_i3.Session>);

  @override
  _i9.Future<_i3.Session?> getSession({
    String? token,
    String? refreshToken,
    _i11.UserId? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [], {
              #token: token,
              #refreshToken: refreshToken,
              #userId: userId,
            }),
            returnValue: _i9.Future<_i3.Session?>.value(),
            returnValueForMissingStub: _i9.Future<_i3.Session?>.value(),
          )
          as _i9.Future<_i3.Session?>);

  @override
  bool validateToken(_i3.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#validateToken, [session]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool validateRefreshToken(_i3.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#validateRefreshToken, [session]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<void> deleteSession(_i11.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [UnitRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnitRepository extends _i1.Mock implements _i13.UnitRepository {
  @override
  _i9.Future<_i11.UnitStatsDto?> getUnitPublicInfo(_i4.UnitId? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitPublicInfo, [unitId]),
            returnValue: _i9.Future<_i11.UnitStatsDto?>.value(),
            returnValueForMissingStub: _i9.Future<_i11.UnitStatsDto?>.value(),
          )
          as _i9.Future<_i11.UnitStatsDto?>);

  @override
  _i9.Future<_i4.UnitDto> createUnit(
    _i11.UserId? userId,
    _i4.CreateUnitDto? dto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUnit, [userId, dto]),
            returnValue: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#createUnit, [userId, dto]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#createUnit, [userId, dto]),
              ),
            ),
          )
          as _i9.Future<_i4.UnitDto>);

  @override
  _i9.Future<_i4.UnitDto?> updateUnit(
    _i11.UserId? userId,
    _i4.UpdateUnitDto? dto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUnit, [userId, dto]),
            returnValue: _i9.Future<_i4.UnitDto?>.value(),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto?>.value(),
          )
          as _i9.Future<_i4.UnitDto?>);

  @override
  _i9.FutureOr<_i4.UnitDto?> getUnit({
    required _i11.UserId? userId,
    required int? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnit, [], {
              #userId: userId,
              #characterId: characterId,
            }),
            returnValueForMissingStub: null,
          )
          as _i9.FutureOr<_i4.UnitDto?>);

  @override
  _i9.FutureOr<List<_i4.UnitDto>> getListUnit({required _i11.UserId? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getListUnit, [], {#userId: userId}),
            returnValue: _i9.Future<List<_i4.UnitDto>>.value(<_i4.UnitDto>[]),
            returnValueForMissingStub: _i9.Future<List<_i4.UnitDto>>.value(
              <_i4.UnitDto>[],
            ),
          )
          as _i9.FutureOr<List<_i4.UnitDto>>);

  @override
  _i9.Future<_i4.UnitDto> setSelectedUnit({
    required _i11.UserId? userid,
    required int? unitId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedUnit, [], {
              #userid: userid,
              #unitId: unitId,
            }),
            returnValue: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#setSelectedUnit, [], {
                  #userid: userid,
                  #unitId: unitId,
                }),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#setSelectedUnit, [], {
                  #userid: userid,
                  #unitId: unitId,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.UnitDto>);

  @override
  _i9.Future<_i4.UnitDto?> getSelectedUnit(_i11.UserId? userid) =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedUnit, [userid]),
            returnValue: _i9.Future<_i4.UnitDto?>.value(),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto?>.value(),
          )
          as _i9.Future<_i4.UnitDto?>);

  @override
  _i9.Future<bool> deleteUnit({
    required _i11.UserId? userId,
    required int? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnit, [], {
              #userId: userId,
              #characterId: characterId,
            }),
            returnValue: _i9.Future<bool>.value(false),
            returnValueForMissingStub: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> updateStats({
    required int? unitId,
    int? winDelta = 0,
    int? lossDelta = 0,
    int? coinDelta = 0,
    int? expDelta = 0,
    int? newLevel,
    int? newStatPoints,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStats, [], {
              #unitId: unitId,
              #winDelta: winDelta,
              #lossDelta: lossDelta,
              #coinDelta: coinDelta,
              #expDelta: expDelta,
              #newLevel: newLevel,
              #newStatPoints: newStatPoints,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> allocateStats(
    int? unitId,
    int? addAtk,
    int? addDef,
    int? addVitality,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#allocateStats, [
              unitId,
              addAtk,
              addDef,
              addVitality,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [UnitDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnitDao extends _i1.Mock implements _i8.UnitDao {
  @override
  _i5.DbClient get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeDbClient_3(
              this,
              Invocation.getter(#attachedDatabase),
            ),
            returnValueForMissingStub: _FakeDbClient_3(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i5.DbClient);

  @override
  _i6.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_4(
              this,
              Invocation.getter(#connection),
            ),
            returnValueForMissingStub: _FakeDatabaseConnection_4(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i6.DatabaseConnection);

  @override
  _i6.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_5(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeDriftDatabaseOptions_5(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i6.DriftDatabaseOptions);

  @override
  _i6.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i14.dummyValue<_i6.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
            returnValueForMissingStub: _i14.dummyValue<_i6.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i6.SqlTypes);

  @override
  _i6.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_6(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeQueryExecutor_6(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i6.QueryExecutor);

  @override
  _i7.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_7(
              this,
              Invocation.getter(#streamQueries),
            ),
            returnValueForMissingStub: _FakeStreamQueryStore_7(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i7.StreamQueryStore);

  @override
  _i6.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_8(
              this,
              Invocation.getter(#resolvedEngine),
            ),
            returnValueForMissingStub: _FakeDatabaseConnectionUser_8(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i6.DatabaseConnectionUser);

  @override
  _i5.$UnitTableTable get unitTable =>
      (super.noSuchMethod(
            Invocation.getter(#unitTable),
            returnValue: _Fake$UnitTableTable_9(
              this,
              Invocation.getter(#unitTable),
            ),
            returnValueForMissingStub: _Fake$UnitTableTable_9(
              this,
              Invocation.getter(#unitTable),
            ),
          )
          as _i5.$UnitTableTable);

  @override
  _i5.$SelectedUnitTableTable get selectedUnitTable =>
      (super.noSuchMethod(
            Invocation.getter(#selectedUnitTable),
            returnValue: _Fake$SelectedUnitTableTable_10(
              this,
              Invocation.getter(#selectedUnitTable),
            ),
            returnValueForMissingStub: _Fake$SelectedUnitTableTable_10(
              this,
              Invocation.getter(#selectedUnitTable),
            ),
          )
          as _i5.$SelectedUnitTableTable);

  @override
  _i8.UnitDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeUnitDaoManager_11(
              this,
              Invocation.getter(#managers),
            ),
            returnValueForMissingStub: _FakeUnitDaoManager_11(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i8.UnitDaoManager);

  @override
  _i9.Future<_i4.UnitDto> insertUnit(_i5.UnitTableCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#insertUnit, [companion]),
            returnValue: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(this, Invocation.method(#insertUnit, [companion])),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(this, Invocation.method(#insertUnit, [companion])),
            ),
          )
          as _i9.Future<_i4.UnitDto>);

  @override
  _i9.Future<int> deleteAllBotUnits(List<String>? botUserIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBotUnits, [botUserIds]),
            returnValue: _i9.Future<int>.value(0),
            returnValueForMissingStub: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<_i4.UnitDto?> getUnitDto({
    required int? unitId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitDto, [], {
              #unitId: unitId,
              #userId: userId,
            }),
            returnValue: _i9.Future<_i4.UnitDto?>.value(),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto?>.value(),
          )
          as _i9.Future<_i4.UnitDto?>);

  @override
  _i9.Future<List<_i4.UnitDto>> getListUnitDto({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getListUnitDto, [], {#userId: userId}),
            returnValue: _i9.Future<List<_i4.UnitDto>>.value(<_i4.UnitDto>[]),
            returnValueForMissingStub: _i9.Future<List<_i4.UnitDto>>.value(
              <_i4.UnitDto>[],
            ),
          )
          as _i9.Future<List<_i4.UnitDto>>);

  @override
  _i9.Future<_i4.UnitDto?> updateUnit(_i5.UnitTableCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#updateUnit, [companion]),
            returnValue: _i9.Future<_i4.UnitDto?>.value(),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto?>.value(),
          )
          as _i9.Future<_i4.UnitDto?>);

  @override
  _i9.Future<int> deleteUnit(int? characterId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnit, [characterId]),
            returnValue: _i9.Future<int>.value(0),
            returnValueForMissingStub: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<_i4.UnitDto> setSelectedUnit(
    _i5.SelectedUnitTableCompanion? companion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedUnit, [companion]),
            returnValue: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#setSelectedUnit, [companion]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#setSelectedUnit, [companion]),
              ),
            ),
          )
          as _i9.Future<_i4.UnitDto>);

  @override
  _i9.Future<_i4.UnitDto?> getSelectedUnitDto(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedUnitDto, [userId]),
            returnValue: _i9.Future<_i4.UnitDto?>.value(),
            returnValueForMissingStub: _i9.Future<_i4.UnitDto?>.value(),
          )
          as _i9.Future<_i4.UnitDto?>);

  @override
  _i9.Future<void> updateStats({
    required int? unitId,
    int? winDelta = 0,
    int? lossDelta = 0,
    int? coinDelta = 0,
    int? expDelta = 0,
    int? newLevel,
    int? newStatPoints,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStats, [], {
              #unitId: unitId,
              #winDelta: winDelta,
              #lossDelta: lossDelta,
              #coinDelta: coinDelta,
              #expDelta: expDelta,
              #newLevel: newLevel,
              #newStatPoints: newStatPoints,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setStats({
    required int? unitId,
    int? wins,
    int? losses,
    int? coins,
    int? exp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setStats, [], {
              #unitId: unitId,
              #wins: wins,
              #losses: losses,
              #coins: coins,
              #exp: exp,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> allocateStats(
    int? unitId,
    int? addAtk,
    int? addDef,
    int? addVitality,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#allocateStats, [
              unitId,
              addAtk,
              addDef,
              addVitality,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i11.UnitStatsDto?> getUnitPublicInfo(int? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitPublicInfo, [unitId]),
            returnValue: _i9.Future<_i11.UnitStatsDto?>.value(),
            returnValueForMissingStub: _i9.Future<_i11.UnitStatsDto?>.value(),
          )
          as _i9.Future<_i11.UnitStatsDto?>);

  @override
  _i9.Stream<T> createStream<T extends Object>(
    _i7.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i9.Stream<T>.empty(),
            returnValueForMissingStub: _i9.Stream<T>.empty(),
          )
          as _i9.Stream<T>);

  @override
  T alias<T, D>(_i6.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
            returnValueForMissingStub: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i6.TableInfo<_i6.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i6.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Stream<Set<_i6.TableUpdate>> tableUpdates([
    _i6.TableUpdateQuery? query = const _i6.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i9.Stream<Set<_i6.TableUpdate>>.empty(),
            returnValueForMissingStub: _i9.Stream<Set<_i6.TableUpdate>>.empty(),
          )
          as _i9.Stream<Set<_i6.TableUpdate>>);

  @override
  _i9.Future<T> doWhenOpened<T>(
    _i9.FutureOr<T> Function(_i6.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(this, Invocation.method(#doWhenOpened, [fn])),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i9.Future<T>);

  @override
  _i6.InsertStatement<T, D> into<T extends _i6.Table, D>(
    _i6.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_13<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
            returnValueForMissingStub: _FakeInsertStatement_13<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i6.InsertStatement<T, D>);

  @override
  _i6.UpdateStatement<Tbl, R> update<Tbl extends _i6.Table, R>(
    _i6.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_14<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
            returnValueForMissingStub: _FakeUpdateStatement_14<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i6.UpdateStatement<Tbl, R>);

  @override
  _i6.SimpleSelectStatement<T, R> select<T extends _i6.HasResultSet, R>(
    _i6.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_15<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeSimpleSelectStatement_15<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i6.SimpleSelectStatement<T, R>);

  @override
  _i6.JoinedSelectStatement<T, R> selectOnly<T extends _i6.HasResultSet, R>(
    _i6.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_16<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeJoinedSelectStatement_16<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i6.JoinedSelectStatement<T, R>);

  @override
  _i6.BaseSelectStatement<_i6.TypedResult> selectExpressions(
    Iterable<_i6.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_17<_i6.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
            returnValueForMissingStub:
                _FakeBaseSelectStatement_17<_i6.TypedResult>(
                  this,
                  Invocation.method(#selectExpressions, [columns]),
                ),
          )
          as _i6.BaseSelectStatement<_i6.TypedResult>);

  @override
  _i6.DeleteStatement<T, D> delete<T extends _i6.Table, D>(
    _i6.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_18<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
            returnValueForMissingStub: _FakeDeleteStatement_18<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i6.DeleteStatement<T, D>);

  @override
  _i9.Future<int> customUpdate(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i6.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i9.Future<int>.value(0),
            returnValueForMissingStub: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> customInsert(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i9.Future<int>.value(0),
            returnValueForMissingStub: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<_i6.QueryRow>> customWriteReturning(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i6.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i9.Future<List<_i6.QueryRow>>.value(<_i6.QueryRow>[]),
            returnValueForMissingStub: _i9.Future<List<_i6.QueryRow>>.value(
              <_i6.QueryRow>[],
            ),
          )
          as _i9.Future<List<_i6.QueryRow>>);

  @override
  _i6.Selectable<_i6.QueryRow> customSelect(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_19<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_19<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i6.Selectable<_i6.QueryRow>);

  @override
  _i6.Selectable<_i6.QueryRow> customSelectQuery(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_19<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_19<_i6.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i6.Selectable<_i6.QueryRow>);

  @override
  _i9.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<T> transaction<T>(
    _i9.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i9.Future<T>);

  @override
  _i9.Future<T> exclusively<T>(_i9.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i9.Future<T>);

  @override
  _i9.Future<void> batch(_i9.FutureOr<void> Function(_i6.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<T> runWithInterceptor<T>(
    _i9.Future<T> Function()? action, {
    required _i6.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
            returnValueForMissingStub:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i9.Future<T>.value(v),
                ) ??
                _FakeFuture_12<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i9.Future<T>);

  @override
  _i6.GenerationContext $write(
    _i6.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_20(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_20(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i6.GenerationContext);

  @override
  _i6.GenerationContext $writeInsertable(
    _i6.TableInfo<_i6.Table, dynamic>? table,
    _i6.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_20(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_20(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i6.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [LettersBroadManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLettersBroadManager extends _i1.Mock
    implements _i15.LettersBroadManager {
  @override
  void createRooms() => super.noSuchMethod(
    Invocation.method(#createRooms, []),
    returnValueForMissingStub: null,
  );

  @override
  void subscribe(_i16.GameSocket? socket, String? n) => super.noSuchMethod(
    Invocation.method(#subscribe, [socket, n]),
    returnValueForMissingStub: null,
  );

  @override
  void newLetter(_i16.GameSocket? socket, _i11.NewLetterRequest? message) =>
      super.noSuchMethod(
        Invocation.method(#newLetter, [socket, message]),
        returnValueForMissingStub: null,
      );

  @override
  void removeLetter(
    _i16.GameSocket? socket,
    _i11.DeleteLetterRequest? message,
  ) => super.noSuchMethod(
    Invocation.method(#removeLetter, [socket, message]),
    returnValueForMissingStub: null,
  );

  @override
  void editLetter(_i16.GameSocket? socket, _i11.EditLetterRequest? message) =>
      super.noSuchMethod(
        Invocation.method(#editLetter, [socket, message]),
        returnValueForMissingStub: null,
      );
}
