// Mocks generated by Mockito 5.4.6 from annotations
// in backend/test/features/bot/chat_debug_test2.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:backend/features/auth/domain/session.dart' as _i3;
import 'package:backend/features/auth/domain/session_repository.dart' as _i8;
import 'package:backend/features/auth/domain/user_repository.dart' as _i5;
import 'package:backend/features/game/domain/unit_repository.dart' as _i9;
import 'package:backend/models/user.dart' as _i2;
import 'package:dto/dto.dart' as _i7;
import 'package:game_dto/game_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_1 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnitDto_2 extends _i1.SmartFake implements _i4.UnitDto {
  _FakeUnitDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i5.UserRepository {
  @override
  _i6.Future<_i2.User?> getUser({
    _i7.UserId? userId,
    String? email,
    String? confirmationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [], {
              #userId: userId,
              #email: email,
              #confirmationToken: confirmationToken,
            }),
            returnValue: _i6.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.User?>.value(),
          )
          as _i6.Future<_i2.User?>);

  @override
  _i6.Future<_i2.User> createUser(_i7.EmailCredentialDto? createUserDto) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [createUserDto]),
            returnValue: _i6.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#createUser, [createUserDto]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#createUser, [createUserDto]),
              ),
            ),
          )
          as _i6.Future<_i2.User>);

  @override
  _i6.Future<_i2.User> loginUser(_i7.EmailCredentialDto? loginUserDto) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [loginUserDto]),
            returnValue: _i6.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#loginUser, [loginUserDto])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#loginUser, [loginUserDto])),
            ),
          )
          as _i6.Future<_i2.User>);

  @override
  _i6.Future<_i2.User> confirmEmail(String? confirmationToken) =>
      (super.noSuchMethod(
            Invocation.method(#confirmEmail, [confirmationToken]),
            returnValue: _i6.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#confirmEmail, [confirmationToken]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#confirmEmail, [confirmationToken]),
              ),
            ),
          )
          as _i6.Future<_i2.User>);

  @override
  _i6.Future<List<_i2.User>> getBots() =>
      (super.noSuchMethod(
            Invocation.method(#getBots, []),
            returnValue: _i6.Future<List<_i2.User>>.value(<_i2.User>[]),
            returnValueForMissingStub: _i6.Future<List<_i2.User>>.value(
              <_i2.User>[],
            ),
          )
          as _i6.Future<List<_i2.User>>);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i8.SessionRepository {
  @override
  _i6.Future<_i3.Session> createSession(_i2.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [user]),
            returnValue: _i6.Future<_i3.Session>.value(
              _FakeSession_1(this, Invocation.method(#createSession, [user])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Session>.value(
              _FakeSession_1(this, Invocation.method(#createSession, [user])),
            ),
          )
          as _i6.Future<_i3.Session>);

  @override
  _i6.Future<_i3.Session> updateSession(_i3.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i6.Future<_i3.Session>.value(
              _FakeSession_1(
                this,
                Invocation.method(#updateSession, [session]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Session>.value(
              _FakeSession_1(
                this,
                Invocation.method(#updateSession, [session]),
              ),
            ),
          )
          as _i6.Future<_i3.Session>);

  @override
  _i6.Future<_i3.Session?> getSession({
    String? token,
    String? refreshToken,
    _i7.UserId? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [], {
              #token: token,
              #refreshToken: refreshToken,
              #userId: userId,
            }),
            returnValue: _i6.Future<_i3.Session?>.value(),
            returnValueForMissingStub: _i6.Future<_i3.Session?>.value(),
          )
          as _i6.Future<_i3.Session?>);

  @override
  bool validateToken(_i3.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#validateToken, [session]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool validateRefreshToken(_i3.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#validateRefreshToken, [session]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> deleteSession(_i7.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UnitRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnitRepository extends _i1.Mock implements _i9.UnitRepository {
  @override
  _i6.Future<_i7.UnitStatsDto?> getUnitPublicInfo(_i4.UnitId? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitPublicInfo, [unitId]),
            returnValue: _i6.Future<_i7.UnitStatsDto?>.value(),
            returnValueForMissingStub: _i6.Future<_i7.UnitStatsDto?>.value(),
          )
          as _i6.Future<_i7.UnitStatsDto?>);

  @override
  _i6.Future<_i4.UnitDto> createUnit(
    _i7.UserId? userId,
    _i4.CreateUnitDto? dto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUnit, [userId, dto]),
            returnValue: _i6.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#createUnit, [userId, dto]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#createUnit, [userId, dto]),
              ),
            ),
          )
          as _i6.Future<_i4.UnitDto>);

  @override
  _i6.Future<_i4.UnitDto?> updateUnit(
    _i7.UserId? userId,
    _i4.UpdateUnitDto? dto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUnit, [userId, dto]),
            returnValue: _i6.Future<_i4.UnitDto?>.value(),
            returnValueForMissingStub: _i6.Future<_i4.UnitDto?>.value(),
          )
          as _i6.Future<_i4.UnitDto?>);

  @override
  _i6.FutureOr<_i4.UnitDto?> getUnit({
    required _i7.UserId? userId,
    required int? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnit, [], {
              #userId: userId,
              #characterId: characterId,
            }),
            returnValueForMissingStub: null,
          )
          as _i6.FutureOr<_i4.UnitDto?>);

  @override
  _i6.FutureOr<List<_i4.UnitDto>> getListUnit({required _i7.UserId? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getListUnit, [], {#userId: userId}),
            returnValue: _i6.Future<List<_i4.UnitDto>>.value(<_i4.UnitDto>[]),
            returnValueForMissingStub: _i6.Future<List<_i4.UnitDto>>.value(
              <_i4.UnitDto>[],
            ),
          )
          as _i6.FutureOr<List<_i4.UnitDto>>);

  @override
  _i6.Future<_i4.UnitDto> setSelectedUnit({
    required _i7.UserId? userid,
    required int? unitId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedUnit, [], {
              #userid: userid,
              #unitId: unitId,
            }),
            returnValue: _i6.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#setSelectedUnit, [], {
                  #userid: userid,
                  #unitId: unitId,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.UnitDto>.value(
              _FakeUnitDto_2(
                this,
                Invocation.method(#setSelectedUnit, [], {
                  #userid: userid,
                  #unitId: unitId,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.UnitDto>);

  @override
  _i6.Future<_i4.UnitDto?> getSelectedUnit(_i7.UserId? userid) =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedUnit, [userid]),
            returnValue: _i6.Future<_i4.UnitDto?>.value(),
            returnValueForMissingStub: _i6.Future<_i4.UnitDto?>.value(),
          )
          as _i6.Future<_i4.UnitDto?>);

  @override
  _i6.Future<bool> deleteUnit({
    required _i7.UserId? userId,
    required int? characterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnit, [], {
              #userId: userId,
              #characterId: characterId,
            }),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> updateStats({
    required int? unitId,
    int? winDelta = 0,
    int? lossDelta = 0,
    int? coinDelta = 0,
    int? expDelta = 0,
    int? newLevel,
    int? newStatPoints,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStats, [], {
              #unitId: unitId,
              #winDelta: winDelta,
              #lossDelta: lossDelta,
              #coinDelta: coinDelta,
              #expDelta: expDelta,
              #newLevel: newLevel,
              #newStatPoints: newStatPoints,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> allocateStats(
    int? unitId,
    int? addAtk,
    int? addDef,
    int? addVitality,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#allocateStats, [
              unitId,
              addAtk,
              addDef,
              addVitality,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
